# Shell variables
# Generated by 'wal'
wallpaper='/home/nekurill/Downloads/wallhaven-d6o77l_1920x1080.png'

# Special
background='#070707'
foreground='#e2e2e2'
cursor='#e2e2e2'

# Colors
color0='#070707'
color1='#777777'
color2='#878787'
color3='#989898'
color4='#A8A8A8'
color5='#B8B8B8'
color6='#C8C8C8'
color7='#e2e2e2'
color8='#9e9e9e'
color9='#777777'
color10='#878787'
color11='#989898'
color12='#A8A8A8'
color13='#B8B8B8'
color14='#C8C8C8'
color15='#e2e2e2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
